# Generated by Django 5.2.12 on 2026-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Viewer'), ('ANALYST', 'Analyst'), ('ADMIN', 'Admin')], default='VIEWER', max_length=20),
        ),
    ]
